version: 2
name: 'Review'
on: [pull_request]
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add reviewers
    reviewers:
      - "skruthara/devteam"
